#pragma config(Sensor, dgtl1,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, sArray3,        sensorTouch)
#pragma config(Sensor, dgtl11, sArray2,        sensorTouch)
#pragma config(Sensor, dgtl12, sArray1,        sensorTouch)
#pragma config(Motor,  port2,           rDrive,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lDrive,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           launcher,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           conveyor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           lLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          intake,        tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

#include "You'veBeenHacked.h" 	// allows me to reference the document
//"You'veBeenHacked.h" in the main code

bool clawPreset;

bool armPreset;

void pre_auton()
{

	bStopTasksBetweenModes = true;
	clawPreset = false;
	armPreset = false;
	// bDisplayCompetitionStatusOnLcd = false;

}

task autonomous()
{
	short Auton;

	if(SensorValue[sArray3] == 0 && SensorValue[sArray2] == 0 && SensorValue[sArray1] == 0)
	{
		Auton = 1;
	}
	else if(SensorValue[sArray3] == 0 && SensorValue[sArray2] == 0 && SensorValue[sArray1] == 1)
	{
		Auton = 2;
	}
	else if(SensorValue[sArray3] == 0 && SensorValue[sArray2] == 1 &&  SensorValue[sArray1] == 0)
	{
		Auton = 3;
	}
	else if(SensorValue[sArray3] == 0 && SensorValue[sArray2] == 1 && SensorValue[sArray1] == 1)
	{
		Auton = 4;
	}
	else if(SensorValue[sArray3] == 1 && SensorValue[sArray2] == 0 && SensorValue[sArray1] == 0)
	{
		Auton = 5;
	}
	else if(SensorValue[sArray3] == 1 && SensorValue[sArray2] == 0 && SensorValue[sArray1] == 1)
	{
		Auton = 6;
	}
	else if(SensorValue[sArray3] == 1 && SensorValue[sArray2] == 1 && SensorValue[sArray1] == 0)
	{
		Auton = 7;
	}
	else
	{
		Auton = 8;
	}
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//                                                                                   AUTON #1																																							///
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//Far Blue Long shot
	if(Auton == 1)
	{
		delay(100);

		motor[lDrive] = 127;
		motor[rDrive] = 10;

		delay(500);

		motor[rDrive] = 127;

		delay(100);

		motor[launcher] = 127;

		delay(200);

		motor[lDrive] = 63;
		motor[rDrive] = 63;

		delay(100);

		motor[lDrive] = 0;
		motor[rDrive] = 0;

		delay(3500);

		motor[launcher] = 0;

	}
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//                                                                                   AUTON #2																																							///
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//Far Red long shot
	if(Auton == 2)
	{
		delay(100);

		motor[lDrive] = 10;
		motor[rDrive] = 127;

		delay(500);

		motor[lDrive] = 127;

		delay(100);

		motor[launcher] = 127;

		delay(200);

		motor[lDrive] = 63;
		motor[rDrive] = 63;

		delay(100);

		motor[lDrive] = 0;
		motor[rDrive] = 0;

		delay(3500);

		motor[launcher] = 0;

		motor[lDrive] = -127;
		motor[rDrive] = 127;

		delay(800);

		motor[lDrive] = 0;
		motor[rDrive] = 0;

		delay(100);

		motor[rDrive] = 63;
		motor[lDrive] = 127;

	}
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//                                                                                   AUTON #3																																							///
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//Close Blue short shot and touch
	else if(Auton == 3)
	{

		motor[rLift] = 127;
		motor[lLift] = 127;

		delay(100);

		motor[rLift] = -30;
		motor[lLift] = -30;

		delay(100);

		motor[rLift] = 0;
		motor[lLift] = 0;
		motor[lDrive] = 127;
		motor[rDrive] = 10;
		motor[launcher] = 127;

		delay(500);

		motor[rDrive] = 127;

		delay(100);

		motor[lDrive] = 0;
		motor[rDrive] = 0;

		delay(3200);

		motor[lDrive] = 127;
		motor[rDrive] = 127;

		delay(100);

		motor[rDrive] = 63;

		delay(100);

		motor[rDrive] = 127;
		motor[lDrive] = 63;

		delay(100);

		motor[lDrive] = 127;

		delay(700);

		motor[lDrive] = 63;
		motor[rDrive] = 63;

		delay(50);

		motor[lDrive] = 0;
		motor[rDrive] = 0;

		delay(50);

		motor[lDrive] = -63;
		motor[rDrive] = -63;

		delay(50);

		motor[lDrive] = -127;
		motor[rDrive] = -127;

		delay(500);

		motor[rDrive] = -10;

		delay(500);

		motor[rDrive] = 127;
		motor[lDrive] = 127;

		delay(500);
////
		motor[rDrive] = -127;
		motor[lDrive] = 127;

		delay(500);

		motor[rDrive] = 127;

		delay(1000);

		motor[rDrive] = 60;

		delay(300);

		motor[lDrive] = 0;
		motor[rDrive] = 0;

		delay(50);

		motor[rLift] = 127;
		motor[lLift] = 127;

		delay(500);

		motor[rLift] = 0;
		motor[lLift] = 0;

		delay(100);

		motor[lDrive] = 127;
		motor[rDrive] = 127;

		delay(200);

		motor[lDrive] = 0;
		motor[rDrive] = 0;

		delay(100);

		motor[rLift] = -30;
		motor[lLift] = -30;

		delay(200);

		motor[rLift] = 10;
		motor[lLift] = 10;

	}
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//                                                                                   AUTON #4																																							///
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//Close Red short shot and touch
	else if(Auton == 4)
	{

		motor[rLift] = 127;
		motor[lLift] = 127;

		delay(100);

		motor[rLift] = -30;
		motor[lLift] = -30;

		delay(100);

		motor[rLift] = 0;
		motor[lLift] = 0;
		motor[rDrive] = 127;
		motor[lDrive] = 10;
		motor[launcher] = 127;

		delay(500);

		motor[lDrive] = 127;

		delay(100);

		motor[lDrive] = 0;
		motor[rDrive] = 0;

		delay(3200);

		motor[lDrive] = 127;
		motor[rDrive] = 127;

		delay(100);

		motor[lDrive] = 63;

		delay(100);

		motor[lDrive] = 127;
		motor[rDrive] = 63;

		delay(100);

		motor[rDrive] = 127;

		delay(700);

		motor[lDrive] = 63;
		motor[rDrive] = 63;

		delay(50);

		motor[lDrive] = 0;
		motor[rDrive] = 0;

		delay(50);

		motor[lDrive] = -63;
		motor[rDrive] = -63;

		delay(50);

		motor[lDrive] = -127;
		motor[rDrive] = -127;

		delay(500);

		motor[rDrive] = -10;

		delay(500);

		motor[rDrive] = 127;
		motor[lDrive] = 127;

		delay(600);

		motor[lDrive] = -127;
		motor[rDrive] = 127;

		delay(500);

		motor[lDrive] = 127;

		delay(1000);

		motor[lDrive] = 60;

		delay(300);

		motor[lDrive] = 0;
		motor[rDrive] = 0;

		delay(50);

		motor[rLift] = 127;
		motor[lLift] = 127;

		delay(500);

		motor[rLift] = 0;
		motor[lLift] = 0;

		delay(100);

		motor[lDrive] = 127;
		motor[rDrive] = 127;

		delay(200);

		motor[lDrive] = 0;
		motor[rDrive] = 0;

		delay(100);

		motor[rLift] = -30;
		motor[lLift] = -30;

		delay(200);

		motor[rLift] = 10;
		motor[lLift] = 10;



	}
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//                                                                                   AUTON #5																																							///
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	else if(Auton == 5)
	{



	}
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//                                                                                   AUTON #6																																							///
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	else if(Auton == 6)
	{



	}
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//                                                                                   AUTON #7																																							///
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	else if(Auton == 7)
	{



	}
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//                                                                                   AUTON #8																																							///
	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	else  if(Auton == 8)
	{



	}
	//AAutonCodePlaceholderForTesting();
}
/*
task Presets()
{
	while(true)
	{

		if(vexRT[Btn8LXmtr2] == 1)
		{
		clawPreset = true;
		clawTurn(claw);
		clawPreset = false;
		}*
		if(vexRT[Btn8RXmtr2] == 1)
		{
			clawPreset = true;
			armPreset = true;
			armLiftHigh(lLift,rLift);
			armPreset = false;
			clawPreset = false;
		}
		if(vexRT[Btn8LXmtr2] == 1)
		{
			armPreset = true;
			armLiftLow(lLift, rLift);
			armPreset = false;
		}

	}
}
*/
task usercontrol()
{
	int Overloaded = 0;			//can be used to give full control to one driver in a match
	//in case of a partner controller failure
	int buttonPressed2 = 0;


	//startTask(Presets);

	// User control code here, inside the loop
	int buttonPressed = 0;
	int intoggle = 0;

	while(true)
	{

		drive(lDrive,rDrive); //void setup in header file

		if(Overloaded == 0)
		{
			if(armPreset == false && vexRT[Ch2Xmtr2] > 10 || armPreset == false && vexRT[Ch2Xmtr2] < 0)
			{
				motor[lLift] = motor[rLift] = vexRT[Ch2Xmtr2];
			}
			else
			{
				motor[lLift] = motor[rLift] = 10;
			}
		}

		//start of intake switch

		if(vexRT[Btn8U] == 1 && buttonPressed == 0 && intoggle == 0 || vexRT[Btn8U] == 1 && buttonPressed == 0 && intoggle == 2)
		{
			intoggle = 1;
			buttonPressed = 1;
		}
		else if(vexRT[Btn8D] == 1 && buttonPressed == 0 && intoggle == 0 || vexRT[Btn8D] == 1 && buttonPressed == 0 && intoggle == 1)
		{
			intoggle = 2;
			buttonPressed = 1;
		}
		else if(vexRT[Btn8U] == 1 && buttonPressed == 0 && intoggle == 1 || vexRT[Btn8U] == 1 && buttonPressed == 0 && intoggle == 2)
		{
			intoggle = 0;
			buttonPressed = 1;
		}
		else if(vexRT[Btn8D] == 1 && buttonPressed == 0 && intoggle == 2 || vexRT[Btn8D] == 1 && buttonPressed == 0 && intoggle == 1)
		{
			intoggle = 0;
			buttonPressed = 1;
		}
		else if(vexRT[Btn8U] == 0 && vexRT[Btn8D] == 0 && buttonPressed == 1)
		{
			buttonPressed = 0;
		}

		//end of intake switch
		//start of overload switch

		if(vexRT[Btn7L] == 1 && Overloaded == 0 && buttonPressed2 == 0)
		{
			Overloaded = 1;
			buttonPressed2 = 1;
		}
		else if(vexRT[Btn7L] == 1 && Overloaded == 1 && buttonPressed2 == 0)
		{
			Overloaded = 0;
			buttonPressed2 = 1;
		}
		else if(vexRT[Btn7L] == 0 && buttonPressed2 == 1)
		{
			buttonPressed2 = 0;
		}

//end of overload switch



		switch(intoggle)
		{
		case 1:
			motor[intake] = 127;
			motor[conveyor] = 30;
			SensorValue[greenLED] = 1;	//for signaling what state
			SensorValue[redLED] = 0;		//is active in testing
			break;

		case 2:
			motor[intake] = -127;
			motor[conveyor] = 0;
			SensorValue[greenLED] = 0;
			SensorValue[redLED] = 1;
			break;

		default:
			motor[intake] = 0;
			motor[conveyor] = 0;
			SensorValue[greenLED] = 0;
			SensorValue[redLED] = 0;
			break;

		}

		if(Overloaded == 1)
		{
			if(vexRT[Btn8U] == 1 && buttonPressed == 0 && intoggle == 0 || vexRT[Btn8U] == 1 && buttonPressed == 0 && intoggle == 2)
			{
				intoggle = 1;
				buttonPressed = 1;
			}
			else if(vexRT[Btn8D] == 1 && buttonPressed == 0 && intoggle == 0 || vexRT[Btn8D] == 1 && buttonPressed == 0 && intoggle == 1)
			{
				intoggle = 2;
				buttonPressed = 1;
			}
			else if(vexRT[Btn8U] == 1 && buttonPressed == 0 && intoggle == 1 || vexRT[Btn8U] == 1 && buttonPressed == 0 && intoggle == 2)
			{
				intoggle = 0;
				buttonPressed = 1;
			}
			else if(vexRT[Btn8D] == 1 && buttonPressed == 0 && intoggle == 2 || vexRT[Btn8D] == 1 && buttonPressed == 0 && intoggle == 1)
			{
				intoggle = 0;
				buttonPressed = 1;
			}
			else if(vexRT[Btn8U] == 0 && vexRT[Btn8D] == 0 && buttonPressed == 1)
			{
				buttonPressed = 0;
			}

			if(vexRT[Btn5U] == 1)
			{
				motor[rLift] = 127;
				motor[lLift] = 127;
			}

			else if(vexRT[Btn5D] == 1)
			{
				motor[rLift] = -127;
				motor[lLift] = -127;
			}

			else
			{
				motor[rLift] = 10;
				motor[lLift] = 10;
			}
			if(vexRT[Btn6D] == 1)
			{
				motor[launcher] = 127;
			}
			else
			{
				motor[launcher] = 0;
			}
		}
		if(vexRT[Btn6DXmtr2] == 1)
		{
			motor[launcher] = 127;
		}
		else
		{
			motor[launcher] = 0;
		}


	}
	//UserControlCodePlaceholderForTesting();
}
